version: "3.9"

services:

  # Spring-Boot backend
  backend:
    build: ./backend               
    env_file: .env                 
    ports:
      - "8080:8080"


  # Vite/React frontend
  frontend:
    build: ./frontend              
    depends_on:
      - backend
    ports:
      - "5173:80"                  

